# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cover_cumulate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cover_cumulate(object):
    def setupUi(self, cover_cumulate):
        cover_cumulate.setObjectName("cover_cumulate")
        cover_cumulate.resize(882, 755)
        self.label = QtWidgets.QLabel(cover_cumulate)
        self.label.setGeometry(QtCore.QRect(50, 10, 551, 41))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(cover_cumulate)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(cover_cumulate)
        self.label_3.setGeometry(QtCore.QRect(100, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(cover_cumulate)
        self.label_4.setGeometry(QtCore.QRect(100, 480, 91, 21))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(cover_cumulate)
        self.pushButton.setGeometry(QtCore.QRect(60, 60, 201, 41))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(cover_cumulate)
        self.label_5.setGeometry(QtCore.QRect(340, 130, 71, 51))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(cover_cumulate)
        self.label_6.setGeometry(QtCore.QRect(350, 300, 72, 15))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(cover_cumulate)
        self.label_8.setGeometry(QtCore.QRect(350, 480, 72, 15))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(cover_cumulate)
        QtCore.QMetaObject.connectSlotsByName(cover_cumulate)

    def retranslateUi(self, cover_cumulate):
        _translate = QtCore.QCoreApplication.translate
        cover_cumulate.setWindowTitle(_translate("cover_cumulate", "Dialog"))
        self.label.setText(_translate("cover_cumulate", "（3）计算前1小时，前2小时，前3小时的累积覆盖率"))
        self.label_2.setText(_translate("cover_cumulate", "前1小时"))
        self.label_3.setText(_translate("cover_cumulate", "前2小时"))
        self.label_4.setText(_translate("cover_cumulate", "前3小时"))
        self.pushButton.setText(_translate("cover_cumulate", "开始计算"))
        self.label_5.setText(_translate("cover_cumulate", "0.253"))
        self.label_6.setText(_translate("cover_cumulate", "0.572"))
        self.label_8.setText(_translate("cover_cumulate", "0.676"))
