# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cover.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1199, 814)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 1111, 91))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 100, 121, 41))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "考虑目标区域是一个经纬度范围。经度75°E-135°E，纬度范围0°N-55°N。则对该区域，计算如下内容：\n"
"（1）计算每个时刻的瞬时覆盖率，并将结果绘制成曲线。\n"
""))
        self.pushButton.setText(_translate("Dialog", "开始计算"))
