# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'draw_cover_cumulate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_draw_cover_cumulate(object):
    def setupUi(self, draw_cover_cumulate):
        draw_cover_cumulate.setObjectName("draw_cover_cumulate")
        draw_cover_cumulate.resize(786, 837)
        self.lineEdit = QtWidgets.QLineEdit(draw_cover_cumulate)
        self.lineEdit.setGeometry(QtCore.QRect(170, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(draw_cover_cumulate)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(draw_cover_cumulate)
        self.label.setGeometry(QtCore.QRect(330, 0, 651, 131))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(draw_cover_cumulate)
        self.line_2.setGeometry(QtCore.QRect(0, 110, 1221, 16))
        font = QtGui.QFont()
        font.setFamily(".PingFang SC")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(draw_cover_cumulate)
        QtCore.QMetaObject.connectSlotsByName(draw_cover_cumulate)

    def retranslateUi(self, draw_cover_cumulate):
        _translate = QtCore.QCoreApplication.translate
        draw_cover_cumulate.setWindowTitle(_translate("draw_cover_cumulate", "Dialog"))
        self.lineEdit.setText(_translate("draw_cover_cumulate", "01:00:00"))
        self.pushButton.setText(_translate("draw_cover_cumulate", "开始计算"))
        self.label.setText(_translate("draw_cover_cumulate", "<html><head/><body><p>请输入一个时刻，格式为01:00:00</p></body></html>"))
